models/Tarefa.py
tarefas=[] #lista de tarefas

def addTarefa(descricao): #função para adicionar tarefa
    id=len(tarefas)+1 #aumenta a lista
    nova_tarefa=Tarefa(id,descricao) #cria uma nova tarefa
    tarefas.append(nova_tarefa) #adiciona a tarefa na lista
"""Tabelas:
Usuários: Nome, e-mail, senha, tipo de usuário (funcionario ou admin).
Tarefas: Nome da tarefa, descrição, data de vencimento, status (pendente, em andamento, concluído).
Categorias de Tarefa: Classificação das tarefas (pessoal, trabalho, estudo, etc.)//
Disciplinas: Nome da disciplina, professor responsável.
Histórico de Tarefas: Registra as alterações nas tarefas (quem alterou, data da alteração)."""
from database import db

class Tarefa(db.Model):
    __tablename__='livros'
    id=db.Column(db.Integer,primary_key=True)
    titulo=db.Column(db.Text,nullable=False)
    descricao=db.Column(db.Text,nullable=False)
    data_entrega=db.Column(db.Date, nullable=False)
    completo=db.Column(db.String(20), nullable=False)
    autor_cod=db.Column(db.Integer, db.ForeignKey('autores.cod'),nullable=False)
    cat_id=db.Column(db.Integer, db.ForeignKey('categorias.id'),nullable=False)
    #relacionamento com Autor
    autor=db.relationship('Autor', back_populates='livro')
    #relacionamento com Categoria
    categoria=db.relationship('Categoria', back_populates='livro')

    def __init__(self, id, titulo,descricao,data_entrega,completo=False):
        self.id=id
        self.titulo=titulo
        self.descricao=descricao
        self.data_entrega=data_entrega
        self.status=completo #tarefa concluida

models/__init__.py
from .Tarefa import * #nome do arquivo 

app.py
from flask import Flask
from database import db, inicializa_db
from controllers.tarefa_controller import tarefas_controller

app = Flask(__name__) 
app.register_blueprint(tarefas_controller)
inicializa_db(app)

if __name__ == '__main__':
  app.run(debug=True)

controllers/__init__.py
from .tarefa_controller import * #nome do arquivo 

controllers/tarefa_controller.py
from flask import Flask, Blueprint, jsonify, render_template, request, redirect, url_for #importa as funções do flask
from models.Tarefa import tarefas, addTarefa #importa as funções do models
from database import db
from models.Tarefa import Tarefa
from repository.tarefaRepository import TarefaRepository

tarefas_controller=Blueprint('tarefa', __name__)
tarefaRepository=TarefaRepository()

@tarefas_controller.route('/') #rota
def index():
    return render_template('index.html', tarefas=tarefas) 
  
@tarefas_controller.route('/add', methods=['POST'])
def add_tarefa():
    descricao=request.form['descricao']
    addTarefa(descricao)
    return redirect(url_for('tarefa.index'))
"""
    titulo=request.json.get("titulo")
    data_publicacao=request.json.get("data_publicacao")
    autor=request.json.get("autor")
    categoria=request.json.get("categoria")
    pags=request.json.get("pags")
    nova_tarefa = tarefaRepository.criar_tarefa(titulo, data_publicacao, autor, categoria, pags)
    return jsonify({'ID': nova_tarefa.id, 'título': novo_tarefa.titulo, 'data da publicação': novo_tarefa.data_publicacao, 'autor': novo_tarefa.autor, 'categoria': novo_tarefa.categoria, 'quantidade de páginas': novo_tarefa.pags}), 201
"""
@tarefas_controller.route('/tarefa/<int:tarefa_id>', methods=['PUT'])
def update_tarefa(tarefa_id):
    data = request.get_json()
    titulo = data.get('titulo')#?
    descricao=data.get("descricao")
    data_entrega = data.get('data_entrega')
    completo=data.get("status")
    updated_tarefa = tarefaRepository.update_tarefa(tarefa_id, titulo, descricao, data_entrega, completo)
    if updated_tarefa:
        return jsonify({'ID': updated_tarefa.id, 'título': updated_tarefa.titulo, 'descricao': updated_tarefa.descricao, 'data de entrega': updated_tarefa.data_entrega, 'status': updated_tarefa.completo})
    return jsonify({'error': 'Tarefa não encontrada'}), 404

@tarefas_controller.route("/consultarT", methods=['GET'])
def consultar_tarefas():
    tarefa=TarefaRepository.buscarTarefaPorID()    
    return jsonify(tarefa.toJSON())

@tarefas_controller.route("/consultarT/<int:tarefa_id>", methods=['GET'])
def consultar_tarefa1(tarefa_id):
    tarefas=tarefaRepository.buscarTarefaPorID(tarefa_id)
    tarefasJSON=[]
    for tarefa in tarefas:
        tarefasJSON.append(tarefa.toJSON())
    return jsonify(tarefasJSON)

@tarefas_controller.route("/delT/<int:tarefa_id>", methods=['DELETE'])
def deletar_tarefa(tarefa_id):
    tarefa_deletada = tarefaRepository.deletarTarefaPorID(tarefa_id)
    if tarefa_deletada:
        return jsonify({'message': 'Tarefa deletada!'})
    return jsonify({'error': 'Tarefa não encontrada'}), 404

dao/__init__.py
from .tarefaDao import * #nome do arquivo 

repository/__init__.py
from .tarefaRepository import * #nome do arquivo 

templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>To Do List</title>
</head>

<body>
    <h1>Lista de Tarefas</h1>
    <ul>
        {% for tarefa in tarefas %}
            <li>{{ tarefa.descricao }} - {% if tarefa.completo %}Completa{% else %}Pendente{% endif %}</li>
            <!-- Exibe a descrição da tarefa e verifica se ela está completa ou pendente -->
        {% endfor %}
    </ul>
    <h1>Adicionar Tarefas</h1>
    <div class="container text-center">
        <form action="/add" method="post" class="row justify-content-center">
            <div class="col-6">
                <div class="input-group">
                    <label for="id">ID:</label>
                    <p>{{ tarefa.id }}</p>
                    <br><br>
                    <label for="titulo">Título:
                        <input type="text" id="titulo" name="titulo" placeholder="Título..."></label>
                    <input type="date" name="data_publicacao" class="form-control" placeholder="Data de Publicação...">
                    <input type="text" name="descricao" class="form-control" placeholder="Descrição da tarefa...">
                    <select id="status" name="status">
                        <option value="1">Completo</option>
                        <option value="2">Em Andamento</option>
                        <option value="3">Pendente</option>
                    </select>
                    <a class="btn-edit" href="{{ url_for('tarefa.add_tarefa') }}">Adicionar<i class="+"></i></a>
                    <a class="btn-edit" href="{{ url_for('tarefa.update_tarefa', id=tarefa.id) }}">Editar<i class="fas fa-pencil-alt"></i></a>
                    <a class="btn-delete" href="{{ url_for('tarefa.deletar_tarefa', id=tarefa.id) }}">Excluir<i class="fas fa-trash-alt"></i></a>
                </div>
            </div>
        </form>
    </div>
</body>

</html>